### ISSUE TITLE
vaclient cannot display inference results from files on remote server

### ISSUE THREAD

**Issue by dingyiyi0226** [dlstreamer/pipeline-server#100]
Hi 
I pull the image from dockerhub and running on a server (192.168.50.70), and I launch the vaclient on local machine (192.168.50.80). I can get the result of avg_fps, but is it possible to sync the `/tmp/results.jsonl` automatically?

<img width="1184" alt="截圖 2022-01-10 22 54 34" src="https://user-images.githubusercontent.com/35497159/148786957-1c7f7663-5f9a-43c8-a4ef-dbfe2742ea3f.png">

**Comment by whbruce** [comment]
In v0.7.1 vaclient can [connect to remote servers](https://github.com/dlstreamer/pipeline-server/blob/master/vaclient/README.md#--server-address) and view results over mqtt by setting appropriate [destination](https://github.com/dlstreamer/pipeline-server/blob/master/vaclient/README.md#--destination) values. This is the recommended option for viewing remote metadata. Setting issue to `wontfix` and will close.

**Comment by dingyiyi0226** [comment]
Thanks
