### ISSUE TITLE
RTSP error - Could not write to resource

### ISSUE THREAD

**Issue by yockgen** [dlstreamer/pipeline-server#114]
I've a RTSP camera is running, and confirm able to access from the host (tested via VLC), however, receiving following error:

{"levelname": "INFO", "asctime": "2022-06-25 11:18:23,224", "message": "Creating Instance of Pipeline object_detection/person_vehicle_bike", "module": "pipeline_manager"}
{"levelname": "ERROR", "asctime": "2022-06-25 11:18:23,501", "message": "Error on Pipeline 868ccefef47811ecbc670242ac110002: gst-resource-error-quark: Could not write to resource. (10): ../gst/rtsp/gstrtspsrc.c(7562): gst_rtspsrc_setup_streams_start (): /GstPipeline:pipeline18/GstURISourceBin:source/GstRTSPSrc:source:\nError (500): Internal Server Error", "module": "gstreamer_pipeline"}

Restful call as below:

curl localhost:8080/pipelines/object_detection/person_vehicle_bike -X POST -H 'Content-Type: application/json' -d '{
    "source": {
        "uri": "rtsp://xxxx:xxxx@192.168.1.226:554/videoMain.sdp",
        "type": "uri"
    },
	"destination": {
        "metadata": {
            "type": "file",
            "format": "json-lines",
            "path": "/tmp/results.jsonl"
        },
        "frame": {
            "type": "rtsp",
            "path": "person-detection"
        }
    }
    
}'

Any advice for next step is appreciated!

**Comment by brmarkus** [comment]
Can you provide more details about your environment (software and hardware), please?
Which version of PipelineServer do you use, how do you use it, how have you configured it, how did you start your usecase?
Looks like a permission-related issue.

**Comment by yockgen** [comment]
This is how I started the pipeline server:

1. git clone https://github.com/dlstreamer/pipeline-server
2. cd /root/pipeline-server
3. ./docker/build.sh
4. docker/run.sh --enable-rtsp -v /tmp:/tmp

I'm using master branch of pipeline-server.

**Comment by whbruce** [comment]
I think decodebin is struggling to deal with your RTSP camera. Switch out the source part of your request for this and let me know how it goes.

```json
  "source": {
      "type": "gst",
      "element": " urisourcebin",
      "properties": {
          "uri": "rtsp://xxxx:xxxx@192.168.1.226:554/videoMain.sdp",
          "latency": 0
      },
      "postproc": "rtph264depay"
  }
```

**Comment by yockgen** [comment]
Thanks! The solution work like a charm.

curl localhost:8080/pipelines/object_detection/person_vehicle_bike -X POST -H 'Content-Type: application/json' -d '{
    "source": {
      "type": "gst",
      "element": " urisourcebin",
      "properties": {
          "uri": "rtsp://xxxxx:xxxxx@192.168.1.226:554/videoMain.sdp",
          "latency": 0
      },
      "postproc": "rtph264depay"
    },
	"destination": {
        "metadata": {
            "type": "file",
            "format": "json-lines",
            "path": "/tmp/results.json1"
        },
        "frame": {
            "type": "rtsp",
            "path": "person-detection"
        }
    }
    
}'
