### ISSUE TITLE
What is the meaning of pipeline status QUEUED and COMPLETE. why some pipeline keep stick at queued state?

### ISSUE THREAD

**Issue by divdaisymuffin** [dlstreamer/pipeline-server#122]
When I am running certain instances, few of them stays stuck at queued state and not able to process further. What conditions trigger queued state?
Is it cpu or memory load? Or issue related to input camera stream?
@whbruce @nnshah1  please help me to understand this behaviour.

**Comment by brmarkus** [comment]
You mean the pipelines are stuck and stay stuck "forever", like a dead-lock?
Do you see it being reproducible? Have you tried increasing debug-level to capture logs?
Do you use gstreamer in a shell, or programmatically (C/C++, Python)?

**Comment by tthakkal** [comment]
@divdaisymuffin 
Pipelines will be in QUEUED state before it starts(RUNNING state).
In what case pipeline could be in  QUEUED state longer?
1.  gstreamer is waiting on resources (CPU/GPU load)
2. MAX_RUNNING_PIPELINES environment variable is set to a number and those number of pipelines are already in RUNNING state, once one of them is COMPLETED, next pipeline will be picked up.
