### ISSUE TITLE
Segfault in libgstvaapi.so

### ISSUE THREAD

**Issue by louisper-intel** [dlstreamer/pipeline-server#125]
ERROR: Caught a segmentation fault while loading plugin file:
/opt/intel/dlstreamer/gstreamer/lib/gstreamer-1.0/libgstvaapi.so

...when running ./docker/run.sh -v /tmp:/tmp to start the server

Log:
Found /dev/dri/renderD128 - enabling GPU
Found /dev/snd - enabling microphone

Running Pipeline Server Image: 'dlstreamer-pipeline-server-gstreamer'
   Models: ''
   Pipelines: ''
   Framework: 'gstreamer'
   Environment: '-e GST_VAAPI_DRM_DEVICE=/dev/dri/renderD128 '
   Volume Mounts: '-v /tmp:/tmp '
   Mode: 'SERVICE'
   Ports: '-p 8080:8080 '
   Name: 'dlstreamer-pipeline-server-gstreamer'
   Network: ''
   Hostname: ''
   Entrypoint: ''
   EntrypointArgs: ''
   User: '--user 1000'
   User Groups: '--group-add 110 --group-add audio --group-add users '
   Devices: '--device /dev/dri/renderD128 --device /dev/snd '
   Device CGroup Rule: ''

{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,817", "message": "==============================", "module": "pipeline_server"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,817", "message": "Options for pipeline_server.py", "module": "pipeline_server"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,817", "message": "==============================", "module": "pipeline_server"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,817", "message": "port == 8080", "module": "pipeline_server"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,817", "message": "framework == gstreamer", "module": "pipeline_server"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,817", "message": "pipeline_dir == pipelines", "module": "pipeline_server"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,817", "message": "model_dir == models", "module": "pipeline_server"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,817", "message": "network_preference == {}", "module": "pipeline_server"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,817", "message": "max_running_pipelines == -1", "module": "pipeline_server"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,817", "message": "log_level == INFO", "module": "pipeline_server"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,817", "message": "config_path == /home/pipeline-server/server/..", "module": "pipeline_server"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,817", "message": "ignore_init_errors == False", "module": "pipeline_server"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,817", "message": "enable_rtsp == False", "module": "pipeline_server"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,817", "message": "rtsp_port == 8554", "module": "pipeline_server"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,817", "message": "enable_webrtc == False", "module": "pipeline_server"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,817", "message": "webrtc_signaling_server == ws://webrtc_signaling_server:8443", "module": "pipeline_server"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,817", "message": "emit_source_and_destination == False", "module": "pipeline_server"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,817", "message": "==============================", "module": "pipeline_server"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,818", "message": "==============", "module": "model_manager"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,818", "message": "Loading Models", "module": "model_manager"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,818", "message": "==============", "module": "model_manager"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,818", "message": "Loading Models from Path /home/pipeline-server/models", "module": "model_manager"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,818", "message": "Loading Model: emotion_recognition version: 1 type: IntelDLDT from {'FP16': '/home/pipeline-server/models/emotion_recognition/1/FP16/emotions-recognition-retail-0
003.xml', 'FP32': '/home/pipeline-server/models/emotion_recognition/1/FP32/emotions-recognition-retail-0003.xml', 'model-proc': '/home/pipeline-server/models/emotion_recognition/1/emotions-recognition-retail-0003.json', 'labels': None
}", "module": "model_manager"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,818", "message": "Loading Model: object_classification version: vehicle_attributes type: IntelDLDT from {'FP16': '/home/pipeline-server/models/object_classification/vehicle_attribu
tes/FP16/vehicle-attributes-recognition-barrier-0039.xml', 'FP32': '/home/pipeline-server/models/object_classification/vehicle_attributes/FP32/vehicle-attributes-recognition-barrier-0039.xml', 'model-proc': '/home/pipeline-server/mode
ls/object_classification/vehicle_attributes/vehicle-attributes-recognition-barrier-0039.json', 'labels': None}", "module": "model_manager"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,819", "message": "Loading Model: object_detection version: person type: IntelDLDT from {'FP16': '/home/pipeline-server/models/object_detection/person/FP16/person-detection-retail-0
013.xml', 'FP32': '/home/pipeline-server/models/object_detection/person/FP32/person-detection-retail-0013.xml', 'model-proc': '/home/pipeline-server/models/object_detection/person/person-detection-retail-0013.json', 'labels': None}",
"module": "model_manager"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,819", "message": "Loading Model: object_detection version: person_vehicle_bike type: IntelDLDT from {'FP16': '/home/pipeline-server/models/object_detection/person_vehicle_bike/FP16
/person-vehicle-bike-detection-crossroad-0078.xml', 'FP32': '/home/pipeline-server/models/object_detection/person_vehicle_bike/FP32/person-vehicle-bike-detection-crossroad-0078.xml', 'model-proc': '/home/pipeline-server/models/object_
detection/person_vehicle_bike/person-vehicle-bike-detection-crossroad-0078.json', 'labels': None}", "module": "model_manager"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,819", "message": "Loading Model: object_detection version: vehicle type: IntelDLDT from {'FP16': '/home/pipeline-server/models/object_detection/vehicle/FP16/vehicle-detection-0202.
xml', 'FP32': '/home/pipeline-server/models/object_detection/vehicle/FP32/vehicle-detection-0202.xml', 'model-proc': '/home/pipeline-server/models/object_detection/vehicle/vehicle-detection-0202.json', 'labels': None}", "module": "mod
el_manager"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,819", "message": "Loading Model: face_detection_retail version: 1 type: IntelDLDT from {'FP16': '/home/pipeline-server/models/face_detection_retail/1/FP16/face-detection-retail-000
4.xml', 'FP32': '/home/pipeline-server/models/face_detection_retail/1/FP32/face-detection-retail-0004.xml', 'model-proc': '/home/pipeline-server/models/face_detection_retail/1/face-detection-retail-0004.json', 'labels': None}", "modul
e": "model_manager"}

{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,819", "message": "Loading Model: audio_detection version: environment type: IntelDLDT from {'FP16': '/home/pipeline-server/models/audio_detection/environment/FP16/aclnet.xml', 'FP32': '/home/pipeline-server/models/audio_detection/environment/FP32/aclnet.xml', 'model-proc': '/home/pipeline-server/models/audio_detection/environment/aclnet.json', 'labels': None}", "module": "model_manager"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,819", "message": "========================", "module": "model_manager"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,819", "message": "Completed Loading Models", "module": "model_manager"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,819", "message": "========================", "module": "model_manager"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,820", "message": "=================", "module": "pipeline_manager"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,820", "message": "Loading Pipelines", "module": "pipeline_manager"}
{"levelname": "INFO", "asctime": "2023-03-28 04:21:20,820", "message": "=================", "module": "pipeline_manager"}

ERROR: Caught a segmentation fault while loading plugin file:
/opt/intel/dlstreamer/gstreamer/lib/gstreamer-1.0/libgstvaapi.so

Please either:
- remove it and restart.
- run with --gst-disable-segtrap --gst-disable-registry-fork and debug.

**Comment by louisper-intel** [comment]
I ran docker/build.sh after pulling from master earlier this week (assume Monday), so it's whatever version that came with it. Is there a published container that I can use instead?

**Comment by akwrobel** [comment]
@louisper-intel was your issue resolved with the docker image?

**Comment by louisper-intel** [comment]
Yup resolved with the prebuilt image
