### ISSUE TITLE
Docker build fails if directory name contains spaces

### ISSUE THREAD

**Issue by whbruce** [dlstreamer/pipeline-server#38]
If there is a space anywhere in the parent directory path, the build will fail.
 
Example: Assume code has been cloned into the directory `/home/user/VA Serving`, build will fail as follows
```
$ docker/build.sh
<snip>
Successfully tagged video-analytics-serving-gstreamer-base:latest
cp: target 'Serving/video-analytics-serving/docker/Dockerfile.env' is not a directory
```

Workaround is to remove spaces from directory name.

**Comment by akwrobel** [comment]
Closing due to age and relevancy with name change spacing is no longer an encountered issue.
