### ISSUE TITLE
Build fails on Windows 10 and WSL

### ISSUE THREAD

**Issue by Surajb007** [dlstreamer/pipeline-server#44]
Below error is observed while executing the command `./docker/build.sh` after cloning the repo on my Windows 10 machine running WSL 1.0.

`can't open file '/home/video-analytics-serving/tools/model_downloader': [Errno 2] No such file or directory`

More details on the error and screenshots can be found here https://github.com/openvinotoolkit/dlstreamer_gst/issues/151 and https://github.com/openvinotoolkit/dlstreamer_gst/issues/151#issuecomment-729211235

Opening the issue here because it is related to video-analytics-serving repo.

**Comment by whbruce** [comment]
WSL is not currently supported. To help us replicate, can I ask two details:
1. can you add exact steps on how you start WSL (e.g. PowerShell, Ubuntu app etc.). 
2. What is output of `echo $UID` at WSL Linux prompt

**Comment by nnshah1** [comment]
@psakamoor I know that recently you had built va serving on WSL - were you using WSL 1.0 or 2.0, and did you have any BKMS you could share?

**Comment by Surajb007** [comment]
@whbruce 

1. I just start my WSL (Ubuntu app) from the start menu
2. Output of `echo $UID`

![image](https://user-images.githubusercontent.com/11753666/110192912-edd11580-7dfe-11eb-879b-3c26532bca76.png)

**Comment by nnshah1** [comment]
@Surajb007 We have recently released 0.4.1 - want to confirm you've tried with the latest release- do you get the same error?

In the past, this article: https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly 

Was useful to double check basic setup, especially the section on ensuing volume mounts work -

**Comment by whbruce** [comment]
v0.7.1 will build and run on Windows 11 and WSL 2 but only supports CPU inference. This will be our supported Windows configuration going forward so closing as `won't fix`.
