### ISSUE TITLE
gvawatermark not displaying overlay bounding box on output video

### ISSUE THREAD

**Issue by amajai** [dlstreamer/pipeline-server#59]
Hello,

I have been experiencing difficulties in outputting a video with bounding box. I created a custom test pipeline with the gvawatermark element added to the pipeline template to add overlay bounding box to the video output. However, after multiple element arrangement within the template, I was still unable to get the output desired. 

This is the template format I used:
```bash
{
	"type": "GStreamer",
	"template": ["urisourcebin name=source ! tee name=t ! queue",
				" ! decodebin ! video/x-raw ! videoconvert name=videoconvert ! queue",
				" ! gvadetect model={models[object_detection][1][network]} name=detection",
				" ! gvametaconvert name=metaconvert ! queue ! gvametapublish name=destination",
				" ! gvawatermark ! appsink name=appsink",
				" t. ! queue ! qtdemux ! splitmuxsink name=splitmuxsink"
				],
	"description": "Object Detection TEST PIPELINE",

}
```

**Comment by nnshah1** [comment]
@amjai - To make sure we understand - your desire is to save the watermarked output as segments? Or jpeg frames?

**Comment by amajai** [comment]
I was thinking the watermarked output would be in the same video format. What are the format of segments?

**Comment by nnshah1** [comment]
The segment recording sample is designed specifically to save the incoming stream without re-encoding it - so it it would be the incoming stream format (for example h264) within an mp4 container (splitmuxsink uses qtmux by default). 

To get a watermarked frame you would need to re-encode the frame before sending it to splitmuxsink 

Something similar to:
`gvawatermark ! videoconvert ! x264enc key-int-max=30 speed-preset=ultrafast tune=zerolatency ! splitmuxsink`

For an example with jpegencoding:

See: 

https://github.com/intel/video-analytics-serving/blob/master/samples/lva_ai_extension/pipelines/object_detection/debug_person_vehicle_bike_detection/pipeline.json

Note: in our next release (end of March) we are adding a "rtsp restreaming" feature to make it simpler to see watermarked frames for debug - so you can get an rtsp stream of your results -

**Comment by amajai** [comment]
Oh I see. But after adding the elements you provided to the template, I got this error.
```bash
{"levelname": "ERROR", "asctime": "2021-02-17 16:34:39,129", "message": "Error Starting VA Serving: Error Initializing Pipelines", "module": "__main__"}
```

**Comment by nnshah1** [comment]
@amajai probably I have a typo / more to put in - can you send the final pipeline you are trying?

**Comment by amajai** [comment]
@nnshah1 This is the template I used:
```bash
	"template": ["urisourcebin name=source ! tee name=t ! queue ! decodebin ! video/x-raw ! videoconvert name=videoconvert",
				" ! queue! gvadetect model={models[object_detection][1][network]} name=detection",
				" ! gvametaconvert name=metaconvert ! queue ! gvametapublish name=destination",
				" ! gvawatermark ! videoconvert ! x264enc key-int-max=30 speed-preset=ultrafast tune=zerolatency ! splitmuxsink"
				],
```

**Comment by nnshah1** [comment]
Try one of the following. The first uses the mjpeg to encode and an avi container. The second uses x264enc plus an mp4 container. The x264enc element may not be installed by default due to licensing issues - in order to use it you may need to install some additional components in the container. Both pipelines are designed to put 30 second clips (either avi or mp4) in the /tmp folder. You can additionally make these configurable via parameters so you can pass in the storage location, similar to what is done here: https://github.com/intel/video-analytics-serving/blob/master/pipelines/gstreamer/object_detection/2/pipeline.json


```
"template": ["urisourcebin name=source ! decodebin ",
				" ! gvadetect model={models[object_detection][1][network]} name=detection",
				" ! gvametaconvert name=metaconvert ! queue ! gvametapublish name=destination",
				" ! gvawatermark ! videoconvert ! avenc_mjpeg ! splitmuxsink muxer=avimux location=\"/tmp/temp-%d.avi\" max-size-time=30000000000"
				],
```
```
"template": ["urisourcebin name=source ! decodebin ",
				" ! gvadetect model={models[object_detection][1][network]} name=detection",
				" ! gvametaconvert name=metaconvert ! queue ! gvametapublish name=destination",
				" ! gvawatermark ! videoconvert ! x264enc ! splitmuxsink location=\"/tmp/temp-%d.mp4\" max-size-time=30000000000"
				],
```

**Comment by amajai** [comment]
@nnsha1 Thanks alot! I got it to work exactly what I wanted. However, the video quality is pretty low and AVI file are usually large. Is there a way to improve the output video quality or  should I try a different element? 
Regarding the `x264enc`  element, how can I generally add components to the container?

**Comment by whbruce** [comment]
Try out our [RTSP re-streaming](https://github.com/intel/video-analytics-serving/blob/master/README.md#real-time-streaming-protocol-rtsp) feature. Does that help you?

**Comment by whbruce** [comment]
Take a look at #82. That may help.

**Comment by whbruce** [comment]
Closing as there has been no response for over a year.
