### ISSUE TITLE
Models can be picked up from previous build 

### ISSUE THREAD

**Issue by whbruce** [dlstreamer/pipeline-server#71]
The wrong model can be included if (1) switching between GStreamr and FFmpeg frameworks or (2) upgrading VA Serving and then building with with existing model cache. Another side effect is container can be larger than necessary due to picking up extra models. 

There are two options for workarounds
* Delete models folder before building
* Use [--force-model-download](https://github.com/intel/video-analytics-serving/blob/master/docs/build_script_reference.md#force-model-download---force-model-download) flag

**Comment by akwrobel** [comment]
Closed due to age and current relevancy
